jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java, jsprit-io/src/test/java/com/graphhopper/jsprit/io/algorithm/TestAlgorithmReader.java
https://app.asana.com/0/327480005138404/486017119316639
related to https://github.com/bringg/jsprit-service/pull/206
=> VehicleRoutingAlgorithms receive cost func in create

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/VehicleTypeDependentJobInsertionCalculator.java
https://app.asana.com/0/240165331568461/534077961656540
https://github.com/bringg/jsprit-service/pull/290
=> add fixed cost to insertion cost

jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java, jsprit-io/src/test/java/com/graphhopper/jsprit/io/algorithm/TestAlgorithmReader.java
https://github.com/bringg/jsprit-service/pull/300
https://app.asana.com/0/240165331568461/533991215111840
=> pass constraintmanager as parameter

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/AbstractInsertionStrategy.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertionConcurrent.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionConcurrent.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/AbstractInsertionStrategyTest.java
https://github.com/bringg/jsprit-service/pull/305
=> add vehicle fixed cost to new routes

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdateMaxTimeInVehicle.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdatePracticalTimeWindows.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdateVehicleDependentPracticalTimeWindows.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTimeWindowConstraints.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/state/UpdateVehicleDependentTimeWindowTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTimeWindowWithStartTimeAndMaxOperationTimeTest.java, jsprit-io/src/test/java/com/graphhopper/jsprit/io/algorithm/TestAlgorithmSquashActivityTimes.java
https://app.asana.com/0/240165331568461/540977127584866
=> pass prev activity

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/termination/VariationCoefficientTermination.java
https://github.com/bringg/jsprit-service/pull/325
=> protected variation coefficient

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/StateManager.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdateMaxTimeInVehicle.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxTimeInVehicleConstraint.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/MaxTimeInVehicleTest.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-31
=> Pass all vehicles

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/VehicleRoutingAlgorithm.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/acceptor/SchrimpfInitialThresholdGenerator.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/UnassignedJobReasonTracker.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/util/UnassignedJobReasonTrackerTest.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java
https://github.com/bringg/jsprit-service/pull/372
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-79
=> MaxTimeInVehicleConstarint added to Unassigned jobs tracker

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/module/RuinAndRecreateModule.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/AbstractInsertionStrategy.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertionConcurrent.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionConcurrent.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionConcurrentFast.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionFast.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/module/RuinAndRecreateModuleTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionTest.java
https://github.com/bringg/jsprit-service/pull/384
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-5
=> InsertBreaksToNewRoutes

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/AbstractInsertionStrategy.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertionConcurrent.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionConcurrent.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionConcurrentFast.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RegretInsertionFast.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-109
https://github.com/bringg/jsprit-service/pull/399
=> Add log to break insertion

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/InsertionBuilder.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RandomInsertion.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/RandomInsertionTest.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/SkillsWithPriorities.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/InsertionFactory.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java, jsprit-io/src/main/resources/algorithm_schema.xsd, jsprit-io/src/test/java/com/graphhopper/jsprit/io/algorithm/SkillsTest.java, jsprit-io/src/test/resources/com/graphhopper/jsprit/io/algorithm/configWithRandomInsert.xml
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-122
=> RandomInsertionAdded

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/JobInsertionCostsCalculatorBuilder.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/ShipmentWithMutablePickupDeliverOptions.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-167
=> multiplePickupDeliverOptions

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/VehicleRoutingAlgorithm.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-162
=> pass_solution_acceptors

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblem.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-165
=> initial solution

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RandomInsertion.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTimeWindowConstraints.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/RandomInsertionTest.java
https://bringg.atlassian.net/browse/BUGS-791
=> include driver can serve task count

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/VehicleTypeDependentJobInsertionCalculator.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/CalcVehicleTypeDependentServiceInsertionTest.java
=> Revert "additionalFixedCost"

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/VehicleTypeDependentJobInsertionCalculator.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/CalcVehicleTypeDependentServiceInsertionTest.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-293
tests in jsprit-service
=> Additional fixed cost

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/VehicleTypeDependentJobInsertionCalculator.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/CalcVehicleTypeDependentServiceInsertionTest.java
https://github.com/bringg/jsprit-service/pull/523
=> Add additional cost to insertion cost

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/AbstractInsertionStrategy.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/InsertionStrategy.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/ConstraintManager.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Job.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Service.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Shipment.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-319
**DO NOT MERGE**
=> driverId_in_service_and_shipment

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/module/RuinAndRecreateModule.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/RandomInsertion.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=BUGS-1022
=> remove empty routes after insertion

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/PrettyAlgorithmBuilder.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/box/Jsprit.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/box/JspritTest.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-328
=> With random insertion in jsprit

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BreakForMultipleTimeWindowsInsertionCalculator.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/JobInsertionCostsCalculatorBuilder.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/ShipmentInsertionCalculator.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/BreakForMultipleTimeWindows.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/BreakForMultipleTimeWindowsActivity.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/DefaultTourActivityFactory.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/ShipmentInsertionCalculatorTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/job/BreakForMultipleTimeWindowsTest.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=BUGS-1044
=> BreakForMultipleTimeWindows

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/vehicle/VehicleImpl.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/vehicle/VehicleTypeKey.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/vehicle/VehicleTypeKeyTest.java
https://bringg.atlassian.net/browse/OPTI-383
=> add_user_data_to_vehicle_type_id

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Shipment.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/PickupShipment.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/job/ShipmentTest.java
https://bringg.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=OPTI&modal=detail&selectedIssue=OPTI-439
=> OPTI-439 pickup_loading_time

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BreakForMultipleTimeWindowsInsertionCalculator.java
=> OPTI-2006 pass_insertion_index
